REGIONS = {
    'us-east-2': 'US East (Ohio)',
    'us-east-1': 'US East (N. Virgina)',
    'us-east': 'US East (N. Virgina)',
    'us-west-1': 'US West (N. California)',
    'us-west-2': 'US West (Oregon)',
    'us-west-2-lax-1a': 'US West (Los Angeles)',
    'us-west': 'US West (Northern California)',
    'ap-northeast-1': 'Asia Pacific (Tokyo)',
    'ap-northeast-2': 'Asia Pacific (Seoul)',
    'ap-northeast-3': 'Asia Pacific (Osaka-Local)',
    'ap-south-1': 'Asia Pacific (Mumbai)',
    'ap-southeast-1': 'Asia Pacific (Singapore)',
    'ap-southeast-2': 'Asia Pacific (Sydney)',
    'apac-sin': 'Asia Pacific (Singapore)',
    'apac-syd': 'Asia Pacific (Sydney)',
    'apac-tokyo': 'Asia Pacific (Tokyo)',
    'ap-east-1': 'Asia Pacific (Hong Kong)',
    'ca-central-1': 'Canada (Central)',
    'cn-north-1': 'China (Beijing)',
    'cn-northwest-1': 'China (Ningxia)',
    'eu-central-1': 'Europe (Frankfurt)',
    'eu-west-1': 'Europe (Ireland)',
    'eu-west-2': 'Europe (London)',
    'eu-west-3': 'Europe (Paris)',
    'eu-ireland': 'Europe (Ireland)',
    'eu-north-1': 'Europe (Stockholm)',
    'sa-east-1': 'South America (São Paulo)',
    'us-gov-west-1': 'AWS GovCloud (US)',
    'me-south-1': 'Middle East (Bahrain)',
    'af-south-1': 'Africa (Cape Town)',
    'eu-south-1': 'Europe (Milan)',
}

INSTANCE_TYPES = {
    'generalCurrentGen': ('General Purpose', 'Current Generation'),
    'generalPreviousGen': ('General Purpose', 'Previous Generation'),
    'computeCurrentGen': ('Compute Optimized', 'Current Generation'),
    'computePreviousGen': ('Compute Optimized', 'Previous Generation'),
    'gpuCurrentGen': ('GPU Instances', 'Current Generation'),
    'hiMemCurrentGen': ('Memory Optimized', 'Current Generation'),
    'Memory Optimized - Previous Generation': ('Memory Optimized', 'Previous Generation'),
    'uI': ('Micro Instances', ''),
    'fpgaCurrentGen': ('FPGA Instances', 'Current Generation'),
}