version: "3"
services:
  aws-pricing:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: aws-pricing.app
    environment: 
      JUPYTER_ENABLE_LAB: 'yes'
    restart: "no"
    network_mode: "host"
    # ports:
    #   - "8501:8501"